call pathogen#infect()

filetype plugin indent on
set tabstop=2
set shiftwidth=2
set expandtab
set autoread
set autoindent
set number
set showmatch
set smarttab
set laststatus=2
set encoding=utf-8
set ruler

let mapleader=','
let g:mapleader=','

colorscheme railscasts
set transparency=5

set gfn=Monaco:h12

autocmd BufWritePre * :%s/\s\+$//e
