ZSH=$HOME/.oh-my-zsh
ZSH_THEME="clean"

plugins=(brew bundler gem git github heroku osx rails3 ruby rvm)

source $ZSH/oh-my-zsh.sh

export ARCHFLAGS="-arch x86_64"
export PATH=/usr/local/bin:$PATH:$HOME/.rvm/bin

# Find in files, usage: fif PATH STRING
function fif() {
  find $1 | xargs grep "$2" -sl
}

# Restore JT dump, usage: jt_restore PATH
function jt_restore() {
  rake db:drop db:create
  pg_restore -j 4 --verbose --clean --no-acl --no-owner -U jobandtalent -d jobandtalent $1
}

function h { heroku $argv[0,-2] --app $argv[-1] }
function hp { h $argv production-jt }
function hs { h $argv staging-jt }
