ZSH=$HOME/.oh-my-zsh
ZSH_THEME="clean"

PATH=/usr/local/share/npm/bin:/usr/local/heroku/bin:/usr/local/bin:$PATH

plugins=(brew bundler gem git github heroku osx rails ruby)

ARCHFLAGS="-arch x86_64"
EDITOR="mvim"
JAVA_OPTS="-Djava.awt.headless=true"
JAVA_HOME=$(/usr/libexec/java_home)

source $ZSH/oh-my-zsh.sh

fpath=(/usr/local/share/zsh-completions $fpath)

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Find in files, usage: fif PATH STRING
function fif() {
  find $1 | xargs grep "$2" -sl
}

function h { heroku $argv[0,-2] --app $argv[-1] }
function hp { h $argv production }
function hs { h $argv staging }

alias emacs='/usr/local/Cellar/emacs/HEAD/Emacs.app/Contents/MacOS/Emacs &'

cotd
