ZSH=$HOME/.oh-my-zsh
ZSH_THEME="clean"

export PATH=$HOME/.cargo/bin:/usr/local/sbin:/usr/local/bin:$PATH

plugins=(brew git osx)

export ARCHFLAGS="-arch x86_64"
export EDITOR="vim"
export GOPATH=$HOME/depot

source $ZSH/oh-my-zsh.sh

fpath=(/usr/local/share/zsh-completions $fpath)

alias dc='docker-compose'
alias dcr='dc run --rm app'
