ZSH=$HOME/.oh-my-zsh
ZSH_THEME="clean"

export PATH=/usr/local/sbin:/usr/local/bin:$PATH

plugins=(git github)

export EDITOR="vim"

source $ZSH/oh-my-zsh.sh

fpath=(/usr/local/share/zsh-completions $fpath)

if which direnv > /dev/null; then eval "$(direnv hook zsh)"; fi

# Find in files, usage: fif PATH STRING
function fif() {
  find $1 | xargs grep "$2" -sl
}

function h { heroku $argv[0,-2] --app $argv[-1] }
function hp { h $argv production }
function hs { h $argv staging }

alias dc='docker-compose'
alias dcr='dc run --rm app'
